name: phone_auth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  country_picker: ^2.0.20
  date_time_format: ^2.0.1
  easy_image_viewer: ^1.2.1
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get: ^4.6.5
  google_sign_in: ^6.1.4
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
  material_design_icons_flutter: ^7.0.7296
  pinput: ^2.3.0
  progress_dialog_null_safe: ^1.0.7
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  sms_autofill: ^2.3.0
  story_view: ^0.15.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/